// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTO6J2KpuyPz24UPoSrMX1Rd-zZ7J5xuQ',
    appId: '1:60088779804:web:c6a2974e25a0e0ca480bd9',
    messagingSenderId: '60088779804',
    projectId: 'codempire-task-flutter',
    authDomain: 'codempire-task-flutter.firebaseapp.com',
    storageBucket: 'codempire-task-flutter.appspot.com',
    measurementId: 'G-YN4197SZW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHzkoaSUrM0PRXyS5HK-xHR8GBBLhcr7o',
    appId: '1:60088779804:android:dadde25029d4044d480bd9',
    messagingSenderId: '60088779804',
    projectId: 'codempire-task-flutter',
    storageBucket: 'codempire-task-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67bM8XGmroU6Rsi9CBwLcZtyRH_zNxmA',
    appId: '1:60088779804:ios:ce9bba577266acd3480bd9',
    messagingSenderId: '60088779804',
    projectId: 'codempire-task-flutter',
    storageBucket: 'codempire-task-flutter.appspot.com',
    iosClientId:
        '60088779804-uoa67r910kq6r933mo5f8sniu55d727s.apps.googleusercontent.com',
    iosBundleId: 'com.example.codempireTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA67bM8XGmroU6Rsi9CBwLcZtyRH_zNxmA',
    appId: '1:60088779804:ios:ce9bba577266acd3480bd9',
    messagingSenderId: '60088779804',
    projectId: 'codempire-task-flutter',
    storageBucket: 'codempire-task-flutter.appspot.com',
    iosClientId:
        '60088779804-uoa67r910kq6r933mo5f8sniu55d727s.apps.googleusercontent.com',
    iosBundleId: 'com.example.codempireTask',
  );
}
